spring:
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  file:
    path: ./logs
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learning?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1025017
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect